# Use root/1234 as user/password credentials
version: '2'

services:

  db:
    image: mysql
    hostname: localhost
    # 向外暴露端口
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

# web端的数据库管理工具
  adminer:
    image: adminer
    restart: always
    hostname: localhost
    ports:
    - 8000:8080
